//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkAssignment.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StudentsContext : DbContext
    {
        public StudentsContext()
            : base("name=StudentsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
    
        public virtual ObjectResult<string> GetCourses()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetCourses");
        }
    
        public virtual ObjectResult<GetEmptyCourses_Result> GetEmptyCourses()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmptyCourses_Result>("GetEmptyCourses");
        }
    
        public virtual ObjectResult<string> GetStudents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetStudents");
        }
    
        public virtual ObjectResult<string> GetTeachers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetTeachers");
        }
    
        public virtual int FireMike()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FireMike");
        }
    
        public virtual int MakeSureMikeIsFired()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MakeSureMikeIsFired");
        }
    
        public virtual ObjectResult<GivingRaise_Result> GivingRaise()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GivingRaise_Result>("GivingRaise");
        }
    
        public virtual ObjectResult<GiveRaiseThirty_Result> GiveRaiseThirty()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GiveRaiseThirty_Result>("GiveRaiseThirty");
        }
    }
}
